eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8886
spring:
  application:
    name: config-client
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  cloud:
    config:
      label: master
     # uri: http://localhost:8888/ #指明配置服务中心的网址
      profile: dev
      discovery:
        enabled: true
        service-id: config-server
management:
  security:
    enabled: false #解决请求/bus/reflash会报权限
