eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8764
spring:
  application:
    name: service-ribbon
  cloud:
    config:
     # uri: http://localhost:8888/
      profile: dev
      label: master
      discovery:
        enabled: true
        service-id: config-server